comment: false
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        # flags:
        #   - unit
        #   - integration
        # paths:
        #   - "src"
        branches:
          - main
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: false
github_checks:
  annotations: false
