---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

- include_tasks: setup.yaml
- include_tasks: build.yaml
- include_tasks: tests.yaml

- name: Release instructions
  ansible.builtin.debug:
    msg: >-
      Build tested and complete!
      A changelog as well as a porting guide have probably been generated at {{ antsibull_data_dir }}.
      The changelog must stay in the ansible-build-data repository and can be sent as a pull request
      but the porting guide needs to be submitted to ansible/ansible-documentation:docs/docsite/rst/porting_guides.
