---
- name: Install antsibull from current source in a virtualenv with poetry
  command: poetry install
  args:
    chdir: "{{ playbook_dir | dirname }}"

- name: Ensure the sdist directory exists
  ansible.builtin.file:
    name: "{{ antsibull_sdist_dir }}"
    state: directory
    mode: 0755

- name: Set expected path to release archive
  ansible.builtin.set_fact:
    _release_archive: "{{ antsibull_sdist_dir }}/ansible-{{ antsibull_ansible_version }}.tar.gz"

- name: Clone the ansible-build-data git repository
  ansible.builtin.git:
    repo: "{{ antsibull_data_git_repo }}"
    dest: "{{ antsibull_data_git_dir }}"
    version: "{{ antsibull_data_version }}"
    # TODO: if we build a release it might change files in this repo
    force: yes

# This is not a rebuild -- if the release archive is already there it won't be re-built if we run again
- name: Build a release tarball with antsibull-build
  command: >
    poetry run antsibull-build single {{ antsibull_ansible_version }} \
      --data-dir {{ antsibull_data_dir }} \
      --sdist-dir {{ antsibull_sdist_dir }} \
      --build-file {{ antsibull_build_file }} \
      --deps-file {{ antsibull_deps_file }}
  # Minimal failure tolerance to galaxy collection download errors
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  args:
    chdir: "{{ playbook_dir | dirname }}"
    creates: "{{ _release_archive }}"

- include_tasks: tests.yaml
