---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

argument_specs:
  main:
    short_description: Build Ansible release package and test it
    version_added: 0.1.0
    description:
      - An Ansible role that builds an Ansible release package with Antsibull and tests it.
    author:
      - David Moreau Simard (@dmsimard)
    options:
      antsibull_build_command:
        description: The command to run C(antsibull-build).
        type: str
        default: antsibull-build

      antsibull_sdist_dir:
        description:
          - The directory where antsibull will build the Ansible release tarball.
        type: path
        default: "{{ playbook_dir | dirname }}/build"

      antsibull_build_file:
        description:
          - The build file.
        type: path
        default: ansible-<major_version>.build

      antsibull_force_rebuild:
        description:
          - Force a rebuild by deleting an existing release tarball and python wheel, if they exist.
        type: bool
        default: false

      antsibull_data_git_repo:
        description:
          - Where to get the L(ansible-build-data,https://github.com/ansible-community/ansible-build-data) repository from.
        type: str
        default: "https://github.com/ansible-community/ansible-build-data"

      antsibull_data_version:
        description:
          - The tag (or branch) of the L(ansible-build-data,https://github.com/ansible-community/ansible-build-data)) git repository to checkout.
          - Could be C(main), C(devel), etc.
        type: str
        default: main

      antsibull_data_reset:
        description:
          - Whether to forcefully reset the ansible-build-data repository.
          - Set to C(false) if there are manual changes that should not be overwritten.
        type: bool
        default: true

      antsibull_data_git_dir:
        description:
          - Where the ansible-build-data git repository will be cloned to.
        type: path
        default: "{{ antsibull_sdist_dir }}/ansible-build-data"

      antsibull_data_dir:
        description:
          - Directory to read C(.build) and C(.deps) files from and write them to.
        type: path
        default: "{{ antsibull_data_git_dir }}/<major_version>"

      antsibull_ansible_version:
        description:
          - The version of ansible to build.
          - For example C(6.3.0), C(7.0.0a1), C(8.0.0rc2).
        type: str
        required: true

      antsibull_ansible_venv:
        description:
          - Where the Ansible release tarball will be installed for test purposes.
        type: path
        default: "{{ antsibull_sdist_dir }}/venv"

      antsibull_venv_cleanup:
        description:
          - Whether or not to start from scratch with a new venv if one exists.
        type: bool
        default: true

      antsibull_tags_validate:
        description:
          - Whether to generate a tags data file as part of the release and
            validate it.
          - This is enabled by default for C(ansible >= 7.2.0).
        type: bool

      antsibull_tags_enforce_policy:
        description:
          - Whether to abort on C(antsibull-build validate-tags-file) errors;
            when False, only warnings are printed.
          - This option is unconditionally enabled for C(ansible >= 9.0.0a1).
          - This option does nothing if O(antsibull_tags_validate) is False.
        type: bool

      antsibull_tags_ignores_file:
        description:
          - File containing a newline separated list of collections to ignore
            when running C(antsibull-build validate-tags-file).
            This file will be ignored if it doesn't exist.
        type: path
        default: "{{ antsibull_data_dir }}/validate-tags-ignores"
