---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Build a single Ansible release
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Include build-release role
      ansible.builtin.include_role:
        name: build-release
