# This workflow will build a simple Sphinx-based docsite

name: Build simple docsite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Monday at 06:00 UTC)
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Use antsibull-docs sphinx-init
        run: |
          antsibull-docs sphinx-init --use-current --dest-dir test-docsite/

      - name: Install dependencies
        run: |
          pip install ansible-core
          pip install -r test-docsite/requirements.txt

      - name: Install collections
        run:
          ansible-galaxy collection install community.docker community.crypto

      - name: Build docsite
        run: |
          test-docsite/build.sh
