---
antsibull_collections_path: "{{ antsibull_ansible_venv }}/lib/{{ _python_version }}/site-packages/ansible_collections"
_antsibull_installed_collections: "{{ _installed_collections_json['stdout'] | from_json }}"
antsibull_installed_collections: "{{ _antsibull_installed_collections[antsibull_collections_path] }}"
